import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Duru_Sans } from "next/font/google";
import "./globals.css";
import Header from "./_components/header/Header";

const duru = Duru_Sans({
  weight: '400',
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={duru.className}>
        <Header />
        {children}

      </body>
    </html>
  );
}
